services:
    service.notify:
        class: 'AppBundle\Service\Notify'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@mrsuh_vk_api"
            - "@service.mail"
            - "@storage.handled_comment"
            - "@storage.comment"
            - "%vk.user_id%"

    service.mail:
        class: 'AppBundle\Service\Mail'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@templating"
            - "@storage.comment"
            - "@storage.handled_comment"
            - "@hash.unsubscribe"
            - "@producer.email"


    model.notify:
        class: 'AppBundle\Model\Notify'
        arguments: ["@doctrine.orm.entity_manager"]

    storage.comment:
        class: 'AppBundle\Storage\CommentStorage'

    storage.handled_comment:
        class: 'AppBundle\Storage\HandledCommentStorage'


# hash start =============================================================================

    hash.unsubscribe:
        class: 'AppBundle\Service\HashService'
        arguments: ['%hash.salt.unsubscribe%', '%hash.min_hash_length%', '%hash.alphabet%']


# hash end ===============================================================================


# ampq consumers start ===================================================================
    #email
    consumer.email:
        class: 'AppBundle\Queue\Consumer\EmailConsumer'
        arguments: ['@mailer', '%mailer_user%']

# ampq consumers end =====================================================================


# ampq producer start ====================================================================

    producer.email:
        class: 'AppBundle\Queue\Producer\EmailProducer'
        arguments: ['@old_sound_rabbit_mq.email_producer']

# ampq producer end =====================================================================

