services:
    service.notify:
        class: 'AppBundle\Service\Notify'
        arguments: ["@doctrine.orm.entity_manager", "@mrsuh_vk_api", "@service.mail", "%user_id%"]

    service.mail:
        class: 'AppBundle\Service\Mail'
        arguments: ["@mailer", "@templating"]

    model.notify:
        class: 'AppBundle\Model\Notify'
        arguments: ["@doctrine.orm.entity_manager"]
